version: "3.8"
services:
  # application service
  app:
    container_name: "yourmeals-app"
    image: app
    environment:
      - MONGODB_URL=mongodb://mongo_db/yourmeals
    volumes:
      - '.:/code'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db

  # database service
  mongo_db:
      image: mongo
      container_name: "yourmeals-mongo-db"
      ports:
        - "27017:27017"
      networks:
        - custom
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${PASSWORD}
      restart: on-failure
      volumes:
        - ${MONGO_VOLUME}:/data/db
networks:
  custom:
    driver: bridge
